boardprj/boardApp/urls.py
from django.urls import path
from . import views

app_name = 'boardApp'

urlpatterns = [
    path('', views.boardMain, name='boardMain'),
    path('createBoard/', views.create_board_multiFile, name='create_board_multiFile'),
    path('detail/<int:board_id>/', views.detail, name='detail'),
]

boardprj/boardprj/urls.py
from django.contrib import admin
from django.urls import path, include
import boardApp.views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

# https://wikidocs.net/71259#3-commonurlspy

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', boardApp.views.index, name='index'),
    path('boardMain/', include('boardApp.urls')),
    path('user/', include('common.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boardprj/common/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

boardprj/boardApp/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

"""
null: db에 null 값을 가질지 정함 (db-related) => 문자열 기반 필드는 사용 불가능!
blank: 유효성 form.is_valid()가 호출될 대 폼 유효성 검사에 사용 (validation-related)
"""
# Create your models here.
class Board(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True)
    body = RichTextUploadingField()

class Comment(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    contents = models.TextField()
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'comments'

class UploadFile(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE, null=True)
    org_file_name = models.TextField(blank=True, default="")
    file = models.FileField(blank=True, null=True, upload_to="%Y/%m/%d/")

boardprj/common/models.py
from django.db import models

# Create your models here.

boardprj/boardApp/forms.py
from django import forms
from django.forms import ClearableFileInput
from .models import Board, Comment, UploadFile
from ckeditor_uploader.widgets import CKEditorUploadingWidget

#Meta 클래스는 내부 클래스로 활용되며, 기본필드의 값을 재정의 할 때 사용.

class CreateBoard(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'body']

        widgets = {
            'title': forms.TextInput(
                attrs={'placeholder': '제목을 입력하세요.'}),
            'body': forms.CharField(widget=CKEditorUploadingWidget()),
        }


class CreateComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['contents']
        widgets = {
            'contents': forms.Textarea(attrs={'class':'form-control', 'rows': 4, 'cols': 40, 'placeholder': 'Join the discussion and Leave a comments!'})
        }

class UploadFileForm(forms.ModelForm):
    class Meta:
        model = UploadFile
        fields = ['file']
        widgets = {
            'file': ClearableFileInput(attrs={'multiple': True, 'style': 'border: 1px solid'})
        }

boardprj/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="Email")

    class Meta:
        model = User
        fields = ("username", "email")

boardprj/boardApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CreateBoard, CreateComment, UploadFileForm
from .models import Board, Comment, UploadFile
from django.core.files.storage import FileSystemStorage
from django.db import connection
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator


# INDEX
def index(request):
    return render(request, 'index.html')


# 게시판 메이페이지
def boardMain(request):
    page = request.GET.get('page', '1')
    board_list = Board.objects.order_by('-id')

    paginator = Paginator(board_list, 10)
    boards = paginator.get_page(page)
    context = {
        'boards': boards
    }

    return render(request, 'boardMain.html', context)


# boad와 파일 여러개 업로드
@login_required(login_url='common:login')
def create_board_multiFile(request):
    if request.method == "POST":
        board_form = CreateBoard(request.POST)
        file_form = UploadFileForm(request.POST, request.FILES)
        if board_form.is_valid():
            new_board = board_form.save(commit=False)
            new_board.author = request.user
            new_board.save()
            board_id = Board.objects.latest('id').id
            if file_form.is_valid():
                files = request.FILES.getlist('file')
                upload_file_list = []
                for f in files:
                    # new_files = file_form.save(commit=False)
                    upload_file_list.append(UploadFile(file=f, board_id=board_id, org_file_name=f.name))
                UploadFile.objects.bulk_create(upload_file_list)
                return redirect('boardApp:boardMain')
    else:
        context = {
            'board_form': CreateBoard(),
            'file_form': UploadFileForm()
        }
        return render(request, 'multiUpload.html', context)


# board 자세히 보기
def detail(request, board_id):
    board_detail = get_object_or_404(Board, pk=board_id)
    comments = Comment.objects.filter(board_id=board_id).order_by('-id')
    upload_file = UploadFile.objects.filter(board_id=board_id).order_by('-id')

    comment_form = CreateComment()


    context = {
        'board_detail': board_detail,
        'upload_file': upload_file,
        'comments': comments,
        'comment_form': comment_form,

    }

    if request.method == "POST":
        comment_form = CreateComment(request.POST)

        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            print(comment_form)
            new_comment.board_id = board_id
            user = request.user
            if user.is_authenticated:
                new_comment.author = user
                #new_comment.save()

    return render(request, 'detail.html', context)

boardprj/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render,redirect
from .forms import UserForm

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')

            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

boardprj/boardApp/templates/boardMain.html
{% extends 'base.html' %}

{% block content %}

<br>
<section style="padding: 100px; text-align: center;">
<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>#</th>
      <th>제목</th>
      <th>작성일</th>
      <th>작성자</th>
      <th>첨부파일</th>
      <th>댓글수</th>
    </tr>
  </thead>
  <tbody>
  {% if boards %}
    {% for board in boards %}
    <tr onClick="location.href='{% url 'boardApp:detail' board.id %}'">
      <td>{{ board.id }}</td>
      <td width="60%">{{ board.title }}</td>
      <td>{{ board.pub_date|date:'Y-m-d' }}</td>
      <td>{{ board.author }}</td>
      <td>{{ board.uploadfile_set.count }}</td>
        <td>{{ board.comment_set.count }}</td>
    </tr>
      {% endfor %}
  {% else %}
  <tr>
    <td colspan="6">게시물이 존재하지 않습니다.</td>
  </tr>
  {% endif %}
    </tbody>
</table>

  <!---------------------------- 페이징 처리----------------------------------------------->
  <ul class="pagination justify-content-center">
      <!-- 이전페이지 -->
      {% if boards.has_previous %}
      <li class="page-item">
          <a class="page-link" href="?page={{ boards.previous_page_number }}">이전</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
      </li>
      {% endif %}

      <!-- 페이지리스트 -->
      {% for page_number in boards.paginator.page_range %}
        {% if page_number >= boards.number|add:-5 and page_number <= boards.number|add:5 %}
          {% if page_number == boards.number %}
          <li class="page-item active" aria-current="page">
              <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
          {% else %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
          {% endif %}
        {% endif %}
      {% endfor %}


      <!-- 다음페이지 -->
      {% if boards.has_next %}
      <li class="page-item">
          <a class="page-link" href="?page={{ boards.next_page_number }}">다음</a>
      </li>
      {% else %}
      <li class="page-item disabled">
          <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
      </li>
      {% endif %}
  </ul>

</section>


{% endblock %}

boardprj/boardApp/templates/createBoard_file.html
{% load static %}
<head>
    <title>게시글 작성</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/board-form.css' %}">
</head>

    {% include "navbar.html" %}

    <main class="form-board">
        <h1>게시글 작성</h1><br/>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label>게시글 제목</label>
        {{ form.title }}
        <br/>
        <label for="username">Author</label>
        <input type="text" readonly style="border: solid 1px" class="form-control-plaintext" id="username" value="{{ user.username }}">
        <br/>
        <label>내용</label>
        {{ form.body }}
        <br/>
        <div class="custom-file">
            <label>첨부파일</label>
            {{ form.file_path }}
        </div>
        <br/>

        <button type="submit">SUBMIT</button>
    </form>
        <br/>
    <button onclick="location.href='{% url 'boardApp:boardMain' %}'">게시글 목록</button>
    </main>

boardprj/boardApp/templates/detail.html
<!DOCTYPE html>
{% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Blog Post - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'css/detail/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/detail/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        {% include "navbar.html" %}
        <!-- Page content-->
        <div class="container mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <br/>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{ board_detail.title }}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on {{ board_detail.pub_date|date:'Y-m-d' }} by {{ board_detail.author }}</div>
                            <!-- Post categories-->
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                        </header>
                        <!-- Preview image figure-->
                        {# <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure> #}
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">
                                {{board_detail.body | safe}}
                            </p>
                            <br/><br/>
                            <hr/>
                            <div class="card bg-light">
                                {% if upload_file %}

                                    <p class="lead" style="margin: 20px;">

                                        {% for uf in upload_file %}
                                            <button onclick="location.href='{{ uf.file.url | safe }}'">파일 다운로드</a> </button>
                                            {{ uf.org_file_name }}
                                        <br/><br/>
                                        {% endfor %}

                                {% else %}
                                    <p class="lead"> 첨부파일이 없습니다
                                {% endif %}

                                </p>
                            </div>
                            <br/>
                            <button class="btn btn-dark" onclick="location.href='{% url 'boardApp:boardMain' %}'" style="margin-left: 780px">목록</a> </button>
                        </section>
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <form class="mb-4" method="POST">
                                    {% csrf_token %}
                                    {{ comment_form }}
                                    <input type="number" value="{{comment.id}}" style="display: none;" name="parent_comment_id">
                                    <br/>
                                    <button {% if not user.is_authenticated %}disabled{% endif %}
                                            class="btn btn-info" type="submit">Leave a Commnet</button>
                                </form>


                                <!-- Comment with nested comments-->
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                        <!-- Child comment 1-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                            </div>
                                        </div>
                                        <!-- Child comment 2-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                When you put money directly to a problem, it makes a good headline.
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <!-- Single comment-->

                                {% for comment in comments %}

                                    <div class="d-flex">
                                        <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." /></div>
                                        <div class="ms-3">
                                            <div class="fw-bold">{{ comment.author }} {{ comment.id }}</div>
                                            <h6 class="ms-3">{{ comment.pub_date|date:'Y-m-d' }} <button onclick="displayForm('reply_form_con_{{comment.id}}');">대댓글 달기</button> </h6>
                                            {{ comment.contents }}
                                        </div>
                                </div>

                                        <div id="reply_form_con_{{comment.id}}" style="display:none;">
                                            <br/>
                                            <form method="POST">
                                                {% csrf_token %}
                                                <input type="number" value="{{comment.id}}" style="display: none;" id="parent_comment_id">
                                                {{ comment_form.contents }}<br/>
                                                <button {% if not user.is_authenticated %}disabled{% endif %}
                                                class="btn btn-secondary" type="submit">REPLY</button>
                                            </form>
                                        </div><br/>
                                {% endfor %}




                            </div>
                        </div>
                    </section>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">Web Design</a></li>
                                        <li><a href="#!">HTML</a></li>
                                        <li><a href="#!">Freebies</a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">JavaScript</a></li>
                                        <li><a href="#!">CSS</a></li>
                                        <li><a href="#!">Tutorials</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>


<script>
    function displayForm(str){
        var formId = str;
        var formstr = 'reply_form_con_'
        {% for comment in comments %}
            var fstr = formstr + {{ comment.id }}
            document.getElementById(fstr).style.display = 'none';
        {% endfor %}
        document.getElementById(formId).style.display = 'block';
    }


</script>

boardprj/boardApp/templates/index.html
<!DOCTYPE html>
<!--
---
layout: examples
title: Cover Template
extra_css:
  - "cover.css"
html_class: "h-100"
body_class: "d-flex h-100 text-center text-white bg-dark"
include_js: false
---

-->
<html class="h-100">
{% load static %}
  <head>
    <title>MAIN</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/cover.css' %}">
</head>

  </head>
<body class="d-flex h-100 text-center text-white bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Cover</h3>
      <nav class="nav nav-masthead justify-content-center float-md-end">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">Features</a>
        <a class="nav-link" href="#">Contact</a>
      </nav>
    </div>
  </header>

  <main class="px-3">
    {% if user.is_authenticated %}
    <h1>환영합니다 &nbsp;{{ user.username }}님</h1>
    {% else %}
    <h1>환영합니다</h1>
    {% endif %}
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="{% url 'boardApp:boardMain' %}"
         class="btn btn-lg btn-secondary fw-bold border-white bg-white">Learn more</a>
    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div>

</body>

</html>

boardprj/boardApp/templates/multiUpload.html
{% load static %}
<head>
    <title>게시글 작성</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/board-form.css' %}">
</head>

    {% include "navbar.html" %}

    <main class="form-board">
        <h1>게시글 작성</h1><br/>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ board_form.media }}
        {{ board_form }}
        {{ file_form }}
        <button type="submit">SUBMIT</button>
    </form>
        <br/>
    <button onclick="location.href='{% url 'boardApp:boardMain' %}'">게시글 목록</button>
    </main>

boardprj/boardprj/templates/base.html
<!DOCTYPE html>
<!---
layout: examples
title: Fixed top navbar example
extra_css:
  - "navbar-top-fixed.css"
--->
{% load static %}
<head>
  <title>Blog Main</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/navbar-top-fixed.css' %}">
  </head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'boardApp:boardMain' %}">Board</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'boardApp:create_board_multiFile' %}">글쓰기</a>
        </li>



        {% comment %}
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
        {% endcomment %}



      </ul>
      <ul class="navbar-nav mb-2 mb-md-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'common:logout' %}"> {{ user.username }}님&nbsp; 로그아웃</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
        </li>
        {% endif %}

      </ul>


      <form class="d-flex">
        {% comment %}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        {% endcomment %}
      </form>
    </div>
  </div>
</nav>

{% block content %}

{% endblock %}

boardprj/boardprj/templates/common/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
<br/>
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
<br/>
{% endif %}

boardprj/boardprj/templates/common/login.html
{% load static %}
<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/signin.css' %}">
</head>

<body class="text-center">
{% include "navbar.html" %}

<main class="form-signin">
  <form method="POST">
    {% csrf_token %}
    <img class="mb-4" src="{% static 'image/bootstrapIcon.png' %}" alt="app icon" width="72" height="72">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="text" class="form-control" id="username" placeholder="username" name="username">
      <label for="username">User ID</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="password" placeholder="Password" name="password">
      <label for="password">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>



  </form>

  <button class="w-100 btn btn-lg btn-dark" onclick="location.href='{% url 'index' %}'">홈페이지</button>

    <p class="mt-5 mb-3 text-muted">If you don't have account <a href="{% url 'common:signup' %}">Sign UP</a></p>


</main>


</body>

boardprj/boardprj/templates/loginServiceCheck.html
{% if user.is_authenticated == false %}
        <script>
            var login= confirm("로그인 후 이용이 가능합니다\n로그인하시겠습니까?");
            if(login==true){
                location.href="{% url 'common:login' %}"
            }else{
                location.href="{% url 'boardApp:boardMain' %}"
            }
        </script>
{% else %}
<script>
        alert("test");
</script>
{% endif %}

boardprj/boardprj/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'boardApp:boardMain' %}">Board</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'boardApp:create_board_multiFile' %}">글쓰기</a>
        </li>

      </ul>
      <ul class="navbar-nav mb-2 mb-md-0">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'common:logout' %}"> {{ user.username }}님&nbsp; 로그아웃</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
        </li>
        {% endif %}

      </ul>

    </div>
  </div>
</nav>